{"uuid": "43265b09-58a6-4f75-8387-00b9e917370b", "children": ["b9a63050-900c-4129-8e5e-1bb3a4b7ad81", "165bb511-d59e-4e2a-90ad-0920417617bf", "4140d80e-b5c3-4798-92e9-0c5644aa86d4", "e673cde2-caea-4ade-87f7-9bc937deb8b0", "1aaaae3b-ec11-4944-be5d-2857be0841cc", "ee337fe6-1bb1-4750-86a6-3a09a2febc5d", "8a7e0482-5f8c-486c-a9ba-7feac7217615", "b4d28800-89a9-4232-b4a8-d4cf492e7eb7", "c2ce83b2-7a7b-4d94-b090-f63ef2654587", "cfa8627d-2909-4902-a085-60bea8bc213b", "03c8124e-b322-4487-83a5-55ab3371126a", "4d467574-fcde-481e-b78e-c16d4c69d8e5", "489e4fd3-f141-4986-8a59-ea13721d23b0", "f1b81cdf-ddee-4b0c-b1df-2780b89a7ba1", "b049aff8-7b1a-42cc-b549-5979378405f1", "f8ebaf48-2bfd-4fd1-b641-1c48e8851f31", "0cdd33a2-9f92-49a6-8609-a3d0b171d940", "14b49c88-1c0d-4ad1-823a-a832a2747a8f", "9def38a6-c525-4ab4-b2b4-556ae68c03fa"], "befores": [{"name": "system_login", "status": "failed", "statusDetails": {"message": "Failed: 接口请求异常，可能是request的连接数过多或请求速度过快导致程序报错！\n", "trace": "  File \"D:\\Develop\\Python\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\Develop\\Python\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"D:\\Develop\\Python\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Develop\\Python\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Develop\\Python\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Develop\\Python\\Lib\\site-packages\\_pytest\\fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Desktop\\pythonproject\\testcase\\conftest.py\", line 30, in system_login\n    RequestBase().specification_yaml(api_info[0][0], api_info[0][1])\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Desktop\\pythonproject\\base\\apiutil.py\", line 98, in specification_yaml\n    res = self.run.run_main(name=api_name, url=url, case_name=case_name, header=header, method=method,\n                            file=files, cookies=cookie, **test_case)\n  File \"D:\\Desktop\\pythonproject\\common\\sendrequest.py\", line 155, in run_main\n    response = self.send_request(method=method,\n                                 url=url,\n    ...<4 lines>...\n                                 verify=False,\n                                 **kwargs)\n  File \"D:\\Desktop\\pythonproject\\common\\sendrequest.py\", line 111, in send_request\n    pytest.fail(\"接口请求异常，可能是request的连接数过多或请求速度过快导致程序报错！\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Develop\\Python\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "接口名称：用户登录", "source": "b737da13-5273-4dc4-8d4c-c560ce79fd98-attachment.txt", "type": "text/plain"}, {"name": "接口地址：http://127.0.0.1:8787/dar/user/login", "source": "af9c078e-8a35-4c92-b36f-eb9e1e68d216-attachment.txt", "type": "text/plain"}, {"name": "请求方法：post", "source": "66c555da-54b4-4c44-a0b6-511673212c75-attachment.txt", "type": "text/plain"}, {"name": "请求头：{'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'}", "source": "85837680-0f76-4305-9f74-92dcc676649e-attachment.txt", "type": "text/plain"}, {"name": "测试用例名称：用户名和密码正确登录验证", "source": "8241fca9-c4bf-49f3-925a-acdb88342340-attachment.txt", "type": "text/plain"}, {"name": "请求参数", "source": "5ee2eeeb-6c75-4a7f-9fce-e283bdd1efb2-attachment.txt", "type": "text/plain"}], "start": 1757841496032, "stop": 1757841498073}], "start": 1757841496032, "stop": 1757841500188}